
services:
  # Основная база данных (main-server)
  postgres-main:
    image: postgres:16.1
    container_name: postgres-main
    environment:
      POSTGRES_DB: main-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "6541:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # База данных для статистики (stats-server)
  postgres-stat:
    image: postgres:16.1
    container_name: postgres-stat
    environment:
      POSTGRES_DB: stats-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "6542:5432"
    volumes:
      - postgres_stat_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Основное приложение (main-server)
  main-service:
    build:
      context: ./ewm-main-service
      dockerfile: Dockerfile
    container_name: main-service
    depends_on:
      postgres-main:
        condition: service_healthy
      stat-service:
        condition: service_healthy
    healthcheck:
      test: curl -f http://ewm-main-service:8080/actuator/health || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-main:5432/main-server
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    restart: unless-stopped

  # Сервис статистики (stat-server)
  stat-service:
    build:
      context: ./stat-svc/stat-server
      dockerfile: Dockerfile
    container_name: stat-service
    depends_on:
      postgres-stat:
        condition: service_healthy
    healthcheck:
      test: curl -f http://stat-server:9090/actuator/health || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-stat:5432/stats-server
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    restart: unless-stopped

volumes:
  postgres_main_data:
  postgres_stat_data: