server:
  port: 9090


spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://stats-server:5432/stats-db
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver
