server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://ewm-service:5555/ewm-db
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver

stats.server:
  url: http://stats-server:9090

app:
  name: ewm-main-service

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.jdbc.bind: TRACE
    ru.practicum: INFO