server:
  port: 8080

stat-server:
  url: http://localhost:9090

app:
  name: ewm-main-service
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/main-server
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.engine.jdbc.spi.SqlStatementLogger: DEBUG
    ru.practicum: DEBUG