DROP TABLE IF EXISTS users, categories;

CREATE TABLE users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(250) NOT NULL,
  email varchar(254) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE categories (
  category_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (category_id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);